### PR TITLE
Alarm option : timer.

### PR DESCRIPTION
**Pull request by Ybbet**
Please create pull requests to the branch `develop`.

* Does the pull request solve an issue (add a reference)?
No
* What are the features of this pr?
Add new alarm option : timer
* Add screenshots for visual changes.
Not needed.

### CODE REVIEW

**Comment by fewieden** [comment]
Thanks @Ybbet for your contribution, it's a nice addition. Please resolve the issues reported by travis ci.

**Comment by Ybbet** [comment]
Hi,
I'll see what I can do. But there seems to be an inconsistency with MagicMirror2. Indeed, on the latter, we must put double quotes. And on this module, we must use simple quotes.

**Comment by fewieden** [comment]
What are those 2 text mp3 files you added?

**Comment by Ybbet** [comment]
Sorry, it was a mistake from my Github Desktop Software.
As for now, we have 2 mp3 files in sounds folder, I added a .gitignore to prevent any future error.

**Pull request merged**
